config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only:[] do
    resources :links
    resources :images
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  # :title, :location, :user_id

  mount_uploader :location, ImageUploader

  belongs_to :user

  default_scope { order('created_at DESC') }

  def random_string
    @randomstring ||= SecureRandom.hex(10)
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  # user_id, name, url

  belongs_to :user

  default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_images_path(:user_id => current_user.id)
  end

  def check_user_permission
    if (!current_user.present? || current_user.id != params[:user_id].to_i)
      redirect_to root_path, notice: I18n.t('errors.no_user_permission')
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_filter :check_user_permission, except: [:index]

  before_filter :set_user_id
  before_filter :set_image_id, :only => [:edit, :update, :destroy]

  def index
    @user = User.find_by_id(@user_id)
    if (@user.blank?)
      redirect_to root_path, notice: I18n.t('errors.absent_collection')
    else
      @images = @user.images

      @self_collection = (current_user.present? && (current_user.id.to_i == @user_id))
    end
  end

  def new
    @image = current_user.images.new
    @user = current_user
  end

  def create
    @image = Image.new(new_image_params)
    @image.user_id = @user_id

    if @image.save
      redirect_to user_images_path(@user_id)
    else
      redirect_to new_user_image_path(@user_id), notice: I18n.t('errors.images.create_error')
    end
  end

  def edit
    @image = Image.find(@image_id)
    @user = current_user
  end

  def update
    @image = Image.find(@image_id)
    if @image.update_column(:title, params[:image][:title])
      redirect_to user_images_path(@user_id)
    else
      redirect_to new_user_image_path(@user_id), notice: I18n.t('errors.images.update_error')
    end
  end

  def destroy
    @image = Image.find(@image_id)
    @image.remove_location!
    @image.delete
    redirect_to user_images_path(@user_id)
  end

  private

  def set_user_id
    @user_id = params[:user_id].to_i
  end

  def set_image_id
    @image_id = params[:id].to_i
  end

  def new_image_params
    params.require(:image).permit(:user_id, :title, :location)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_filter :authenticate_user!, except: [:index]
    before_filter :check_user_permission, except: [:index]

    before_filter :set_user_id
    before_filter :set_link_id, :only => [:edit, :update, :destroy]

    def index
        @links = @user.links

        @self_collection = (current_user.present? && (current_user.id.to_i == @user_id))
    end

    def new
        @link = Link.new
    end

    def create
        @link = Link.new(new_link_params)
        @link.user_id = @user_id

        if @link.save
            redirect_to user_links_path(@user_id)
        else
            redirect_to new_user_link_path(@user_id), notice: I18n.t('errors.links.create_error')
        end
    end

    def edit
    end

    def update
        if @link.update_attributes(edit_link_params)
            redirect_to user_links_path(@user_id)
        else
            redirect_to edit_user_link_path(@user_id, @link_id), notice: I18n.t('errors.links.update_error')
        end
    end

    def destroy
        @link = Link.find(@link_id)
        @link.delete
        redirect_to user_links_path(@user_id)
    end

    private

    def set_user_id
        @user_id = params[:user_id].to_i
        @user = User.find(@user_id)
    end

    def set_link_id
        @link_id = params[:id].to_i
        @link = Link.find(@link_id)
    end

    def new_link_params
        params.require(:link).permit(:user_id, :url, :name)
    end

    def edit_link_params
        params.require(:link).permit(:url, :name)
    end
end

app/views/home/index.html.haml
%h1
  Тестовое задание
%p
  Реализация коллекции ссылок и картинок с возможностью делиться.

app/views/images/edit.html.haml
%h2{:align => 'center'}
  = I18n.t('image_labels.edit_title')
.form-container
  = form_for [@user, @image], :html => { :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "title" }
        = I18n.t('image_labels.title')
      = f.text_field :title, class: 'form-control', value: @image.title
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('image_labels.save')

app/views/images/index.html.haml
%h2
  - if @self_collection
    = I18n.t('your_collection')
  - else
    = I18n.t('collection')
= render partial: 'shared/collection_tabs', locals: { tab: 'images' }
- if @self_collection
  = link_to new_user_image_path(@user_id) do
    %button.btn.btn-primary.btn-actions
      = I18n.t('new')
#blueimp-gallery.blueimp-gallery
  .slides
  %h3.title
  %a.prev ‹
  %a.next ›
  %a.close ×
  %a.play-pause
  %ol.indicator
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", :type => "button"} ×
          %h4.modal-title
        .modal-body.next
        .modal-footer
          %button.btn.btn-default.pull-left.prev{:type => "button"}
            %i.glyphicon.glyphicon-chevron-left{'data-unicode' => 'e079'}
            Previous
          %button.btn.btn-primary.next{:type => "button"}
            Next
            %i.glyphicon.glyphicon-chevron-right{'data-unicode' => 'e080'}
#links
  - if @images.present?
    - @images.each do |img|
      %div.image-list-container
        %a.image-list-link{"data-gallery" => "", :href => img.location.url, :title => img.title}
          %img.image-list-img{:alt => img.title, :src => img.location.thumb.url}/
        - if @self_collection
          %div.image-list-actions-container
            %div.image-list-actions
              = link_to edit_user_image_path(@user_id, img.id) do
                %span.glyphicon.glyphicon-edit
              = link_to user_image_path(@user_id, img.id), :method => :delete, :data => {:confirm => I18n.t("delete_sure")} do
                %span.glyphicon.glyphicon-remove

app/views/images/new.html.haml
%h2{:align => 'center'}
  = I18n.t('image_labels.new_title')
.form-container
  = form_for [@user, @image], :html => { :multipart => true, :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "location" }
        = I18n.t('image_labels.location')
      = f.file_field :location, :style => 'width: 30%px;', class: 'form-control'
    .form-group
      %label{ for: "title" }
        = I18n.t('image_labels.title')
      = f.text_field :title, class: 'form-control'
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('image_labels.save')

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to I18n.t('menu.home'), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li
    = link_to I18n.t('menu.collection'), user_images_path(current_user)

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li
    = link_to I18n.t('menu.logout'), destroy_user_session_path, :method => :delete
- else
  %li
    = link_to I18n.t('menu.login'), new_user_session_path
  %li
    = link_to I18n.t('menu.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Test Eduson'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Test Eduson'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/links/edit.html.haml
%h2{:align => 'center'}
  = I18n.t('links_labels.edit_title')
.form-container
  = form_for [@user, @link], :html => { :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "url" }
        = I18n.t('links_labels.url')
      = f.text_field :url, class: 'form-control', value: @link.url
    .form-group
      %label{ for: "name" }
        = I18n.t('links_labels.name')
      = f.text_field :name, class: 'form-control', value: @link.name
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('links_labels.save')

app/views/links/index.html.haml
%h2
  - if @self_collection
    = I18n.t('your_collection')
  - else
    = I18n.t('collection')
= render partial: 'shared/collection_tabs', locals: { tab: 'links' }
- if @self_collection
  = link_to new_user_link_path(@user_id) do
    %button.btn.btn-primary.btn-actions
      = I18n.t('new')
%table.table.table-bordered.table-condensed.table-striped
  %tr
    %th
      Ссылка
    %th
      Когда добавлена
    - if @self_collection
      %th
        Действия
  - if @links.present?
    - @links.each do |link|
      %tr
        %td
          = link_to link.name, link.url, target: '_blank'
        %td
          = link.created_at
        - if @self_collection
          %td
            = link_to edit_user_link_path(@user_id, link.id) do
              %span.glyphicon.glyphicon-edit
            = link_to user_link_path(@user_id, link.id), :method => :delete, :data => {:confirm => I18n.t("delete_sure")} do
              %span.glyphicon.glyphicon-remove

app/views/links/new.html.haml
%h2{:align => 'center'}
  = I18n.t('links_labels.new_title')
.form-container
  = form_for [@user, @link], :html => { :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "url" }
        = I18n.t('links_labels.url')
      = f.text_field :url, class: 'form-control'
    .form-group
      %label{ for: "name" }
        = I18n.t('links_labels.name')
      = f.text_field :name, class: 'form-control'
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('links_labels.save')

app/views/shared/_collection_tabs.html.haml
%ul.nav.nav-tabs
  %li{:class => (tab == 'images' ? 'active' : nil)}
    = link_to I18n.t('images'), user_images_path(@user_id)
  %li{:class => (tab == 'links' ? 'active' : nil)}
    = link_to I18n.t('links'), user_links_path(@user_id)